### ISSUE TITLE
Can't loop over benchmarks?

### ISSUE THREAD

**Issue by ngoldbaum** [vstinner/perf#42]
I'm confused about why this script crashes:

```python
import perf

setup = {
    'run1': 'data = [1, 2, 3]',
    'run2': 'data = [4, 5, 6]',
}

runner = perf.Runner()

for package in setup:
    print(package)
    runner.timeit(
        name=package,
        stmt="data[1]",
        setup=setup[package],
    )
```

For me, I get the following output:

```
run2
run2
run1
.run1
run2
Error when running timeit benchmark:

Statement:
'data[1]'

Setup:
'data = [4, 5, 6]'

Traceback (most recent call last):
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_timeit.py", line 203, in bench_timeit
    runner.bench_time_func(name, timer.time_func, **kwargs)
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_runner.py", line 458, in bench_time_func
    return self._main(task)
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_runner.py", line 428, in _main
    bench = self._master()
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_runner.py", line 551, in _master
    bench = Master(self).create_bench()
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_master.py", line 221, in create_bench
    worker_bench, run = self.create_worker_bench()
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_master.py", line 135, in create_worker_bench
    self.bench.add_runs(worker_bench)
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_bench.py", line 589, in add_runs
    self.add_run(run)
  File "/home/goldbaum/.virtualenvs/yt-dev/lib/python3.4/site-packages/perf/_bench.py", line 449, in add_run
    % (key, value, run_value))
ValueError: incompatible benchmark, metadata name is different: current=run2, run=run1
```

I gather that `runner.timeit` doesn't block until the tests it's running are done? That was surprising to me. Is there any way I can add a synchronization barrier between benchmark runs? Or is there really no way to loop over a set of benchmarks?

**Comment by vstinner** [comment]
perf spawns subprocesses. The iteration order is randomized by default in
Python 3. Use sorted() somewhere to get reproducible results.

**Comment by ngoldbaum** [comment]
Even if I add sorted() this still crashes because the two benchmarks are running simultaneously.

For now I’m running `perf` itself in a subprocess which seems to serialize the benchmarks as I expected this example to do.

**Comment by ngoldbaum** [comment]
Oh! never mind. It totally doesn't crash with sorted, sorry!
